FROM conanio/clang40
ARG RESTCLIENT_VERSION=0.4.4
ARG boost_version=1.63.0
ARG boost_dir=boost_1_63_0
ENV boost_version ${boost_version}
ADD _builds/linux/bin/example /app/example
ADD _builds/linux/lib/libmaestro.so /usr/lib/libmaestro.so
WORKDIR /app
ENV MAESTRO_SCHEDULER_NAME test
ENV MAESTRO_ROOM_NAME room1
ENV MAESTRO_API_URL localhost:5000
CMD ["/app/example"]
