FROM conanio/clang13-ubuntu18.04

ARG CMAKE_VERSION=3.30.5
ARG BOOST_VERSION=1.86.0
ARG BOOST_DIR=boost_1_86_0

RUN sudo apt-get update && sudo apt-get -y install build-essential libboost-dev curl libcurl4-openssl-dev

# Install CMake
RUN sudo rm -rf /usr/bin/cmake
RUN wget https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-Linux-x86_64.sh \
      -q -O /tmp/cmake-install.sh \
      && sudo chmod u+x /tmp/cmake-install.sh \
      && sudo mkdir /usr/bin/cmake \
      && sudo /tmp/cmake-install.sh --skip-license --prefix=/usr/bin/cmake \
      && rm /tmp/cmake-install.sh
ENV PATH="/usr/bin/cmake/bin:${PATH}"

# Upgrade Conan to 2.9.1 version
RUN pip install conan>=2.9.1 --upgrade

VOLUME /app-src
WORKDIR /app-src
ENTRYPOINT ["/bin/bash"]
