FROM conanio/clang40
ARG RESTCLIENT_VERSION=0.4.4
ARG boost_version=1.63.0
ARG boost_dir=boost_1_63_0
ENV boost_version ${boost_version}
RUN sudo apt-get update && sudo apt-get -y install build-essential libboost-dev cmake
VOLUME /app-src
WORKDIR /app-src
ENTRYPOINT ["/bin/bash"]
